# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be4f4b92768d1ad7da68804abbd434919a6cf993589b1ae04adac7e4301cb0549b21e535d5d4a9a9061df76723ba296e7826c50b9ff5308c8f3e6c2c0dbb7d38

test:
  secret_key_base: d88746308eb23d21e4b00aab1b9c9f89ea7d0c5a9a26becfb5347c8189a8120f8798666a51c9c036998ffdd4f7bddc7a5aa0b47f93827208636a60475cc45d40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
